---
title: "322 Study Design Project"
author: "Kathleen Zhang, Yura Heo"
date: "October 20th, 2025"
format: 
  pdf:
    documentclass: article
    fontsize: 11pt
geometry: margin=1in
execute: 
  warning: false
  message: false
  echo: false
---

# 1. 
What is an estimate of the total number of undergraduate students enrolled in colleges?
 Design your survey with the goal of answering this question most accurately.
 
 - Stratified SRS of colleges
 - Strata based school size and public/private
 - 6 strata 
 - sort by name
 
 # 2. 
 What fraction of colleges have a major in statistical science? Use your sample to estimate
 this fraction; do not get the answer by filtering the schools.
 
 - Stratified SRS of colleges
 - Strata based school size and public/private
 - 6 strata 
 - sort by name
 
 # 3. 
 What is the average of the median earnings among alumni from public schools? From private
 schools (combine for profit and not for profit private schools)?
 
 
 - Stratified SRS for acceptance rate 4 categories

 
 
 # 4. 
  Answer one other question that interests you from the data that you could collect from the
 website.
 
 
 NOrth Carolina undergrad students: average annual cost proportional to student faculty ratio